-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 21:11:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Document_Manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Document_Manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Document_Manager` DEFAULT CHARACTER SET utf8 ;
USE `Document_Manager` ;

-- -----------------------------------------------------
-- Table `Document_Manager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Document_Manager`.`User` (
  `idUser` INT NOT NULL,
  `userFirstName` VARCHAR(45) NULL,
  `userLastName` VARCHAR(45) NULL,
  `userEmail` VARCHAR(45) NULL,
  `userPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Document_Manager`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Document_Manager`.`File` (
  `idFileAuto` INT NOT NULL,
  `idUserUpload` INT NOT NULL,
  `idUserLastViewed` INT NOT NULL,
  `fileTag` VARCHAR(45) NOT NULL,
  `fileName` VARCHAR(45) NOT NULL,
  `fileContent` VARBINARY(500) NOT NULL DEFAULT '0',
  `dateFileUpload` DATETIME NOT NULL,
  `dateLastViewed` TIMESTAMP NOT NULL,
  `fileActive` VARCHAR(45) BINARY NULL DEFAULT '1',
  INDEX `idUser_idx` (`idUserUpload` ASC) VISIBLE,
  UNIQUE INDEX `fileUploadDate_UNIQUE` (`dateFileUpload` ASC) VISIBLE,
  PRIMARY KEY (`idFileAuto`),
  INDEX `userLastViewed_idx` (`idUserLastViewed` ASC) VISIBLE,
  CONSTRAINT `idUserUpload`
    FOREIGN KEY (`idUserUpload`)
    REFERENCES `Document_Manager`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userLastViewed`
    FOREIGN KEY (`idUserLastViewed`)
    REFERENCES `Document_Manager`.`File` (`idUserUpload`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Document_Manager`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Document_Manager`.`Log` (
  `idLog` INT NOT NULL,
  `idUser` INT NULL,
  `idDocument` INT NULL,
  `logType` VARCHAR(45) NULL,
  `logDescription` VARCHAR(1000) NULL,
  PRIMARY KEY (`idLog`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idDocument_idx` (`idDocument` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `Document_Manager`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDocument`
    FOREIGN KEY (`idDocument`)
    REFERENCES `Document_Manager`.`File` (`idFileAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Document_Manager`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Document_Manager`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

CREATE USER 'root' IDENTIFIED BY 'pwd';

GRANT ALL ON `Document_Manager`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
